# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Mod
mod_version=0.1.0-alpha
mod_group=com.regenverse
mod_id=regenverse
mod_name=ReGenVerse
mod_author=jfaparicio
mod_description=Periodically re-seeds world generation outside a protected spawn zone.
mod_license=MIT

# Dependencies
minecraft_version=1.21.1
loader_version=0.18.4
fabric_version=0.116.7+1.21.1
